name: Matrix Barrier Demo

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        # job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        job: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
          11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
          21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
          31, 32, 33, 34, 35, 36, 37, 38, 39, 40
        ]
    runs-on: ubuntu-latest
    env:
      # GIST_ID: 3550e7eaeee9fc6ac1f22e8d79e791e0
      # GIST_TOKEN: PkFmUgSPpkyWd4jobnKfuEoULFfudT2NBWhj
      TOTAL_JOBS: 5
      MATRIX_JOB: ${{ matrix.job }}
      SOCKET_SERVER_URL: http://43.133.204.21:3000
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: Step 1 - Prepare
        run: echo "Job ${{ matrix.job }} doing prepare step"

      - name: Barrier sync
        run: |
          sleep 100

      - name: Step 2 - Continue
        run: echo "Job ${{ matrix.job }} passed barrier and is continuing"
