name: Call Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      start:
        description: "起始 job 编号"
        required: true
        default: 1
        type: number
      count:
        description: "job 数量"
        required: true
        default: 40
        type: number

jobs:
  call-matrix-workflow:
    uses: Buc014960kPearson/Buc014960kPearson/.github/workflows/dynamic-matrix-runner.yml@main
    with:
      start: "${{ inputs.start }}"
      count: "${{ inputs.count }}"